name = "movie-explorer"
compatibility_date = "2026-04-05"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

workers_dev = true
preview_urls  = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_BASE_URL = "https://movie-explorer.workers.dev"